version: '3.4'

services:
  marketplace.api:
    image: ${DOCKER_REGISTRY-}marketplaceapi
    build:
      context: .
      dockerfile: Src/MarketPlace.API/Dockerfile

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
